name: Terraform Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      -name: Test Pipeline variables
        run: |
          echo "Test Pipeline variables":
          echo "AWS_REGION: ${{ secrets.AWS_REGION }}"
          echo "AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}"

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create terraform.tfvars.json
        run: |
          echo '{
            "aws_access_key_id": "${{ secrets.AWS_ACCESS_KEY_ID }}",
            "aws_secret_access_key": "${{ secrets.AWS_SECRET_ACCESS_KEY }}",
            "aws_session_token": "${{ secrets.AWS_SESSION_TOKEN }}",
            "bucket_name": "${{ secrets.AWS_BUCKET }}",
            "region_default": ${{ secrets.AWS_REGION }},
            "account_id": "${{ secrets.AWS_ACCOUNT_ID }}"
          }' > terraform.tfvars.json

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0 # Specify the version you need

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars.json

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=terraform.tfvars.json
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var-file=terraform.tfvars.json